export const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_MOODS_REQUEST = 'FETCH_MOODS_REQUEST';
export const FETCH_MOODS_SUCCESS = 'FETCH_MOODS_SUCCESS';
export const FETCH_MOODS_FAILURE = 'FETCH_MOODS_FAILURE';

export const FETCH_DATES_REQUEST = 'FETCH_DATES_REQUEST';
export const FETCH_DATES_SUCCESS = 'FETCH_DATES_SUCCESS';
export const FETCH_DATES_FAILURE = 'FETCH_DATES_FAILURE';

export const SELECT_USER = 'SELECT_USER';
export const SELECT_TIMESTAMP = 'SELECT_TIMESTAMP';

export const SET_PROPERTY = 'SET_PROPERTY';
export const ADD_MOOD = 'ADD_MOOD';
